version: "3"

services:
  server:
    image: ghcr.io/boriselec/rimworld_artaiserver:main
    container_name: server
    ports: 
      - "8080:8080"
    volumes:
      - "./images:/mnt/images"
    environment:
      - GENERATOR_URL=http://generator:8081/generate
  generator:
    image: ghcr.io/boriselec/rimworld_artaistablediffusion:main
    container_name: generator
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
